# Introduction

## Motivation 

Many of ICSPR's datasets are available in tabular formats that are ready to be imported into standard statistical software packages for analysis. In many cases, it is possible to visualize the data in these tabular datasets on a map (even if such visualizations are not explicitly a part of the original analysis or the replication materials archived by ICPSR). In this tutorial, we will provide a brief example-driven overview of how ICPSR users can represent tabular information from an ICSPR dataset on a map, using the R programming language. The tutorial does not presuppose any previous experience with data analysis, visualization, or programming. 

Why map ICPSR data to begin with? Students and researchers often use data archived at ICPSR as a starting point for exploration and discovery. Indeed, the data that others have collected can often inspire novel questions and hypotheses. It is also the case that the social and political processes studied by the researchers who archive their data with ICPSR are intrinsically spatial; after all, these processes necessarily occur somewhere on the surface of the earth! Placing these social and political processes in their spatial context can therefore bring the data that is stored in tabular datasets to life in dramatic ways, helping us to quickly notice patterns, identify puzzles, and generate hypotheses that would have otherwise remained obscure. In addition to using ICPSR data to generate ideas and explore patterns in existing data, students and researchers may want to reuse ICPSR data and incorporate them into their own ongoing research projects; in reusing this data, they may find it helpful to make publishable maps that they can use in their own papers and projects. 

## Scope and Objectives 

By working through the following tutorial, students and researchers will learn how to spatially visualize existing ICPSR data, with a view towards exploring ICPSR datasets of interest, as well as creating publishable maps derived from ICPSR data that can be used in their papers and projects. The  tutorial also includes practice exercises that can be used as part of a classroom exercise or homework assignment, or as an informal way to test one's understanding.  

It is important to emphasize that this is not a tutorial on Geographic Information Systems (GIS) writ large, and we do not cover important GIS concepts such as map projections and coordinate reference systems. If you need to use advanced mapping and spatial analysis in your work, you should learn these technical foundations (which are beyond the scope of our lesson here). It is also not a tutorial on the principles of cartography, which is a complex art and science that is also beyond our scope; however, the tutorial *will* show you how to customize maps in R, and you can use these skills (after reading up on cartography on your own) to make maps that conform to sound cartographic design principles. Our goal here is not to make works of art, but to quickly create functional and informative maps that are useful to social scientists. 

